### ISSUE TITLE
Is this plugin ready??

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/Q2A-Ultimate-SEO#2]
You have started this plugin we all are waiting for this to be released but you never told whether this plugin is complete or not. Please tell whether this plugin is complete with all the features and what are all the features of this plugin?? And most importantly please release this plugin in q2a as many people there are waiting for this plugin.

**Comment by gurjyot** [comment]
Hello Towhidn, is this plugin compatible to Q2A 1.7??

**Comment by Towhidn** [comment]
I was actually planning to spend next few days to check all my plugins to make them Q2A 1.7 compatible and even publish a new q2a theme(demo at [Humble Tips](http://humble.tips/ "Q2A Theme for tips & tricks") ).

**Comment by gurjyot** [comment]
That's great news... :)
