### ISSUE TITLE
XSS security breach when allowing answer content as meta description

### ISSUE THREAD

**Issue by HTCode** [Towhidn/Q2A-Ultimate-SEO#9]
Hello,

If you enable the option that put the content of the answer (most voted or selected) in meta description your site will be exposed to a possible XSS. Indeed, you are not correctly escaping special characters that comes from the content of the answer. For instance, I have tested the following: if the answer contains some code (inside a pre tag) which contains the character " (double quote) then this character will be displayed as it is in the content of the meta tag (which eventually allows me to writing any HTML/Js content).
I hope that you will understand the matter and correct it in your plugin.

Best regards,
Rafik.

**Comment by Towhidn** [comment]
I assumed that this content was already sanitized by Q2A. Thanks for reporting Rafik.

**Comment by HTCode** [comment]
Welcome. I see that you have corrected this issue now. If so, you can close this issue.
